name: mock_gps_detector
description: Detect selected mock location app and developer options status on Android.
version: 1.0.0
homepage: https://github.com/samiraTR/mock_gps_detector
repository: https://github.com/samiraTR/mock_gps_detector
issue_tracker: https://github.com/samiraTR/mock_gps_detector/issues

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.mock_gps_detector
        pluginClass: MockGpsDetectorPlugin
